### ISSUE TITLE
User can create a question

### ISSUE THREAD

**Issue by t-walker** [t-walker/RSO-Survey#13]
The user (just any user at this point, don't worry about admin controls) should be able to create a question as well as having four possible answers.

**Comment by czhanacek** [comment]
Why four?

**Comment by t-walker** [comment]
I meant to say 2, 3, or 4 possible answers

**Comment by czhanacek** [comment]
Yes but why four max?

**Comment by t-walker** [comment]
I guess we could do more; but I think anything more than 4 is going to be too busy.

**Comment by t-walker** [comment]
@seattlecoder9 can you jump on this?
