### ISSUE TITLE
The survey should display questions and answers 

### ISSUE THREAD

**Issue by t-walker** [t-walker/RSO-Survey#14]
Questions should have an additional field called "order" on them. This is an integer value that lets us move questions around.

The survey should render all the partial views of each question in the survey.

**Comment by t-walker** [comment]
@czhanacek if you're doing this can you assign it to yourself? also what's the progress on this?

**Comment by czhanacek** [comment]
Hey sorry about the delay it's been a busy past few days.
I just committed some code that will display all the questions as rendered partials. Next up is adding the corresponding answers to display in each partial. However, I don't think the relationship between the questions and answers is in the database schema yet so I need to do that first.

**Comment by t-walker** [comment]
I think that this is actually going to be a little bit more complicated. We might have to create a model or something for a "response" because otherwise the form is going to record the responses into another survey which we don't want.

**Comment by t-walker** [comment]
but since we can see the q's and a's on the screen, I'm going to close this out
