### ISSUE TITLE
Determine which routes we need.

### ISSUE THREAD

**Issue by t-walker** [t-walker/RSO-Survey#3]

**Comment by seattlecoder9** [comment]
As far as required views, I think we'll need one for each of the following:

1. Home/Landing page (student)
2. Organization info pages (Maybe?)
3. Admin login page
     a.  Add/remove clubs from database
     b.  Upload CSV file
     c.  Manage Questions/Attributes
     d.  Add/remove admin privileges
4. Survey Page
5. Results page (option for mailer) 

Can you guys think of any additional requirements from Colleen?

**Comment by t-walker** [comment]
I think that's a good place to get started.
