### ISSUE TITLE
Investigate recommendation systems 

### ISSUE THREAD

**Issue by t-walker** [t-walker/RSO-Survey#36]
https://github.com/Pathgather/predictor

I looked at this and I think that might be a good one to start with. @seattlecoder9 can you take this on and see if we can make it work for us?

**Comment by t-walker** [comment]
@seattlecoder9 what's the status of this?

**Comment by t-walker** [comment]
@seattlecoder9 status?

**Comment by czhanacek** [comment]
I don't really know anything about Redis but I found another recommendation engine that we can use that uses the Slope One algorithm. I watched a few YouTube videos (https://www.youtube.com/watch?v=LWAY_XeoQoc was the best) and it seems like a good fit for what we're trying to do. I'm going to toy around with [this implementation for ruby](https://github.com/ashleyw/Slope-One) and let you know how it goes.
