### ISSUE TITLE
Define what information we need to capture about organizations 

### ISSUE THREAD

**Issue by t-walker** [t-walker/RSO-Survey#6]
In the CSV we have the name, short name and the category but if we need to capture anything else it needs to be reflected in the model.

**Comment by czhanacek** [comment]
Keywords for the club? This would be a "many to many" relationship, since one club could have multiple keywords and one keyword could describe multiple clubs.

**Comment by seattlecoder9** [comment]
We also talked about getting some form of contact info from an officer who adds questions in case we need to follow up with them for anything, so Email address?

**Comment by seattlecoder9** [comment]
A brief description of when and where each club meets could be displayed after the quiz is complete. I think that would be a pretty nice feature.

**Comment by t-walker** [comment]
We probably won't build that into the table for now, but we can keep it as an option afterwards; good thinking.
